In [1]:
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt


In [7]:
X = np.array([[3.1,7.2], [4, 6.7], [2.9, 8], [5.1, 4.5], [6, 5], [5.6, 5], [3.3, 0.4], [3.9, 0.9], [2.8, 1], [0.5, 3.4], [1, 4], [0.6, 4.9]])
y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [8]:
classifier = linear_model.LogisticRegression(solver = 'liblinear', C=1)

In [9]:
classifier.fit(X, y)

LogisticRegression(C=1, solver='liblinear')

In [10]:
def visualize_classifier(classifier, X, y):
    min_x, max_x = X[:, 0].min() - 1.0, X[:, 0].max() + 1.0
    min_y, max_y = X[:, 1].min() - 1.0, X[:, 1].max() + 1.0

In [12]:
visualize_classifier(classifier, X, y)

In [15]:
min_x, max_x = X[:, 0].min() - 1.0, X[:, 0].max() + 1.0
min_y, max_y = X[:, 1].min() - 1.0, X[:, 1].max() + 1.0

In [16]:
mesh_step_size = 0.01
x_vals, y_vals = np.meshgrid(np.arange(min_x, max_x, mesh_step_size), np.arange(min_y, max_y, mesh_step_size))

In [18]:
np.c_[x_vals.ravel(), y_vals.ravel()]

array([[-0.5 , -0.6 ],
       [-0.49, -0.6 ],
       [-0.48, -0.6 ],
       ...,
       [ 6.97,  8.99],
       [ 6.98,  8.99],
       [ 6.99,  8.99]])

In [26]:
x_vals.ravel()

array([-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99])

In [25]:
x_vals

array([[-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99],
       [-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99],
       [-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99],
       ...,
       [-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99],
       [-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99],
       [-0.5 , -0.49, -0.48, ...,  6.97,  6.98,  6.99]])

In [21]:
min_x

-0.5

In [22]:
max_x

7.0